-------------------------------------------------------------------------------
Test set: adelina.luxtravel.SomeClassIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.358 s <<< FAILURE! - in adelina.luxtravel.SomeClassIT
example  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on adelina.luxtravel.domain.Excursion.transports references an unknown entity: java.util.Set
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on adelina.luxtravel.domain.Excursion.transports references an unknown entity: java.util.Set

